## 서비스 설정
service:
    name: board
    version: V0.0.1

## 서버 설정
server:
    port: 8080
#  servlet:
#    context-path: /
## Spring 설정
spring:
    profiles:
        active: dev
    servlet:
        multipart:
            ## 멀티파트 업로드 지원여부 (default: true)
            enabled: true
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.password: ''
spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.use_sql_comments: true

FAIL_ON_EMPTY_BEANS: false
active: dev
enabled: true
file-size-threshold: 1MB
jackson: ''
jwt:
    secret: godaejwt
location: ${user.home}/${service.name}/tmpfiles
logging:
    level:
        org:
            hibernate:
                type:
                    descriptor:
                        sql: trace


