INSERT INTO TBL_BOARD ( BOARD_SEQ, BOARD_SUBJECT, BOARD_WRITER, BOARD_CONTENT ) VALUES ( 1, '제목_01', '작성자_01', '내용_01');

INSERT INTO TBL_BOARD ( BOARD_SEQ, BOARD_SUBJECT, BOARD_WRITER, BOARD_CONTENT) VALUES ( 2, '제목_02', '작성자_02', '내용_02');

INSERT INTO TBL_BOARD ( BOARD_SEQ, BOARD_SUBJECT, BOARD_WRITER, BOARD_CONTENT) VALUES ( 3, '제목_03', '작성자_03', '내용_03');

INSERT INTO TBL_BOARD ( BOARD_SEQ, BOARD_SUBJECT, BOARD_WRITER, BOARD_CONTENT) VALUES ( 4, '제목_04', '작성자_04', '내용_04');
